env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2016
  sourceType: module
plugins:
  - prettier
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - error
  "@typescript-eslint/no-unused-vars":
  - warn
  - argsIgnorePattern: "^_"

settings:
  react:
    version: detect
  react-hooks:
    rules-of-hooks: never
    exhaustive-deps: never
