pull_request_rules:
  - name: backport patches to cryostat-v4.1 branch
    conditions:
     - base=main
     - label=backport
    actions:
      backport:
        branches:
          - cryostat-v4.1
        assignees:
          - "{{ author }}"

  - name: auto label PRs from reviewers
    conditions:
      - author=@reviewers
    actions:
      label:
        add:
          - safe-to-test

  - name: dismiss stale reviews
    conditions:
      - base=main
    actions:
      dismiss_reviews:
        approved: [ 'mergify', 'Mergifyio' ]
        changes_requested: [ 'mergify', 'Mergifyio' ]

  - name: request reviews from the reviewers team
    conditions:
      - label=review-requested
    actions:
      request_reviews:
        teams:
          - "@cryostatio/reviewers"

  - name: set reviewers for pull requests that update web-client
    conditions:
      - or:
        - files=src/cryostat-web
        - files~=src/cryostat-web/
    actions:
      request_reviews:
        teams:
          - "@cryostatio/maintainers"

  - name: remove review-requested label upon reviewing
    conditions:
      - or:
        - "#approved-reviews-by>0"
        - "#changes-requested-reviews-by>0"
        - "#commented-reviews-by>0"
    actions:
      label:
        remove:
          - review-requested
