name: Pull Request CI

on:
  merge_group:
  pull_request:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    with:
      container-archs: amd64
