name: CI

on:
  merge_group:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  get-build-info:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - id: tag
        name: Get package.json version
        run: echo "tag=$(jq -r '.version' < package.json)" >> $GITHUB_OUTPUT
  build:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    needs: [get-build-info]
    with:
      push-container: true
      additional-tags: ${{ github.ref_name }} ${{ needs.get-build-info.outputs.tag }}
