name: CI

on:
  merge_group:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      # container-archs: amd64, arm64
      # TODO build multiarch. This is extremely slow since a lot of cross-compilation needs to be done, and image layer caching is not set up or well supported.
      container-archs: amd64
      push-container: true
