name: CI

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci.yaml
        with:
          container-archs: amd64, arm64
